### ISSUE TITLE
Type-ahead filtered input box

### ISSUE THREAD

**Issue by mattrpav** [redhat-ipaas/ipaas-datamapper#11]
iPaaS team-

We need a type-ahead input box for the mapping side panel field names. We found this MIT Licensed module, and wanted to confirm that it is suitable for inclusion with the iPaaS product. Alternatively, it looks like we'll need to implement one from scratch.

https://www.npmjs.com/package/ng2-typeahead

Thanks,
Matt

**Comment by gashcrumb** [comment]
We're already using ng2-bootstrap which has a typeahead implementation -> http://valor-software.com/ng2-bootstrap/#/typeahead

**Comment by mattrpav** [comment]
That'll work
