### ISSUE TITLE
Move UI module to it's own repo?

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-datamapper#15]
I think it might make it easier to bring in the datamapper UI stuff if the frontend code was in it's own git repo, I'd be fine repurposing this one one for it -> https://github.com/redhat-ipaas/datamapper-ui

**Comment by mattrpav** [comment]
Yep, agreed. Does it make sense to park/branch/tag the old sample module somewhere?

**Comment by gashcrumb** [comment]
Yeah, lemme do that real quick...

**Comment by gashcrumb** [comment]
There we go, done, Let me know if I need to open up privs, or a PR against that repo would work too...

**Comment by mattrpav** [comment]
Done.  See ipaas/datamapper-ui
