### ISSUE TITLE
Don't check in node_modules

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-datamapper#16]
Best BTW not to check in your `node_modules` directory, also as a follow-on use `yarn` to manage dependencies and check in the `yarn.lock` file which will help fix transitive dependencies

**Comment by mattrpav** [comment]
1. node_modules: Missed the .gitignore on my part, I'll clean it up

2. Sounds good. Do you have any BP or reference for us to align with the rest of iPaaS?

**Comment by gashcrumb** [comment]
I would grab the dependencies listed in our package.json -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/package.json

Unfortunately I've not yet come across a good way to externalize deps/dev deps from package.json

**Comment by gashcrumb** [comment]
This can be closed I think...
