### ISSUE TITLE
Set 'main' and 'types' parameters in package.json

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-datamapper#17]
This will need to be set so we can import the data mapper module in the project's package.json:

```
  "main": "src/app/lib/ipaas-data-mapper/data.mapper.module.ts",
  "typings": "src/app/lib/ipaas-data-mapper/data.mapper.module.ts",
```

It may be worth using an `index.ts` file so that any required/replated types/functions/classes needed for configuration could be exported as well.  With this then we can import the module like:

```
import { DataMapperModule } from 'ipaas.data.mapper';
```

**Comment by gashcrumb** [comment]
Oh, also `DataMapperAppComponent` needs to be listed in DataMapperModule's exports, I'm assuming that `DataMapperAppExampleHostComponent` would be our blueprint for using the datamapper.

Would you like a PR for this stuff btw?

**Comment by mattrpav** [comment]
We are reviewing the change requests and will have feedback shortly.

**Comment by gashcrumb** [comment]
@mattrpav any news?  am itchin' to get this on a page :-)

**Comment by mattrpav** [comment]
Yep, we wrapped coding yesterday on the modularization changes, and are doing a last bit of testing. We plan on importing to the -ui repo today.

**Comment by mattrpav** [comment]
Changes committed. See latest code: https://github.com/redhat-ipaas/datamapper-ui/

**Comment by mattrpav** [comment]
Ok to close, per Stan on IRC
