### ISSUE TITLE
iPaaS provided POM to classpath features

### ISSUE THREAD

**Issue by mattrpav** [redhat-ipaas/ipaas-datamapper#19]
Supported

1. Pass a pom file to generate classpath used at design time for Java class inspection
2. Pom file may reference to a parent pom
3. iPaaS is responsible for ensuring the parent pom is correctly resolvable 
4. iPaaS is responsible for ensuring the PATH environment is set for 'java', 'mvn' binaries and other supported environment variables such as: JAVA_HOME, M2_HOME, MAVEN_OPTS, etc
5. Repositories, username+password and proxies for remote dependencies will be handled by the iPaaS setup
6. For Java-to-Java mapping: Both source and target classes will use the same pom file 

Unsupported

1. Child Module projects. Child projects won't be able to resolve and will result in a failed mvn execution
2. Maven Profiles. The mvn command will run with the default profile (no -P specified)

**Comment by mattrpav** [comment]
Hiram- Everything look good to you in the above statements?

**Comment by chirino** [comment]
Looks good to me!

**Comment by mattrpav** [comment]
Excellent.. thanks
