### ISSUE TITLE
Maven build fails

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-datamapper#2]
$ mvn -Pfull clean install
    Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0
    [INFO] Scanning for projects...
    [ERROR] [ERROR] Some problems were encountered while processing the POMs:
    [FATAL] Non-resolvable parent POM for com.mediadriver.atlas:atlas2.java.model:[unknown-version]: Could not find artifact com.mediadriver.atlas:atlas2.java.parent:pom:1.9.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 10
    [FATAL] Non-resolvable parent POM for com.mediadriver.atlas:atlas2.java.inspect:[unknown-version]: Could not find artifact com.mediadriver.atlas:atlas2.java.parent:pom:1.9.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10
    @ 
    [ERROR] The build could not read 2 projects -> [Help 1]
    [ERROR]   
    [ERROR]   The project com.mediadriver.atlas:atlas2.java.model:[unknown-version] (/Users/chirino/sandbox/ipaas-datamapper/atlas2.java.parent/atlas2.java.model/pom.xml) has 1 error
    [ERROR]     Non-resolvable parent POM for com.mediadriver.atlas:atlas2.java.model:[unknown-version]: Could not find artifact com.mediadriver.atlas:atlas2.java.parent:pom:1.9.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 10 -> [Help 2]
    [ERROR]   
    [ERROR]   The project com.mediadriver.atlas:atlas2.java.inspect:[unknown-version] (/Users/chirino/sandbox/ipaas-datamapper/atlas2.java.parent/atlas2.java.inspect/pom.xml) has 1 error
    [ERROR]     Non-resolvable parent POM for com.mediadriver.atlas:atlas2.java.inspect:[unknown-version]: Could not find artifact com.mediadriver.atlas:atlas2.java.parent:pom:1.9.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
    [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by mattrpav** [comment]
Issue should be resolved

Root cause: some pre-existing files were not overwritten with the commit last Friday.

Tested:
1. Deleted local Maven cache (~/.m2/repository/com/mediadriver/atlas)
2. Did a fresh checkout from ipaas-datamapper
3. Built 'full' profile:  mvn -Pfull clean install

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 23.100 s
> [INFO] Finished at: 2017-03-14T16:55:36-05:00
> [INFO] Final Memory: 52M/518M
> [INFO] ------------------------------------------------------------------------

**Comment by mattrpav** [comment]
Hiram confirmed build works via email 3/15 @ 9:47am CT
