### ISSUE TITLE
Deployment is missing some jars

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-datamapper#20]
https://github.com/redhat-ipaas/ipaas-rest/issues/242

**Comment by KurtStam** [comment]
@mattrpav The package name of the connector is com.redhat.ipaas. Also the sub package structure is slightly different then what you have, for salesforce at least. So I think I will need an update atlas mapping.json from you to reflect this.

**Comment by mattrpav** [comment]
@KurtStam can you provide me the GAV coordinates, or a sample build so I can update our iTests accordingly?

**Comment by KurtStam** [comment]
Build fails due to snapshot dependency: https://github.com/redhat-ipaas/connectors/issues/25

**Comment by KurtStam** [comment]
@mattrpav Here you go: https://github.com/KurtStam/ipaas-datamapper/commit/0648139da1dd38d59e637731cf46adfef5af0005#diff-48c560bbb8f61d82574c2887b65b498fR142

**Comment by mattrpav** [comment]
Heads up-- I'm blocked on being able to resolve and download transitive dependencies.
