### ISSUE TITLE
datamapper UI module usage

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-datamapper#3]
Hey there!  Just wanted to find out what the plan is for using the datamapper UI module in the scope of the ipaas UI.  I think with the current setup it'll be difficult, as I believe you run into problems when pulling in an angular module that depends on `BrowserModule`.  It may be necessary to make the app module fairly light and instead use a sub-module for all the functionality in the datamapper.

That was the intent of this skeleton code, see here the main app module doesn't really have any components, but adds ExampleModule as a dependency -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/dev-app/app/app.module.ts

And `ExampleModule` contains and exports all the functionality in the component -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/lib/example/example.module.ts

This module is exported then from the component here -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/lib/index.ts

Which then means a consumer of the component can do:

```
import { ExampleModule } from 'datamapper-ui';
```

Assuming `datamapper-ui` is the node package name.  

Actually second question here, is the plan to publish this in the npm registry, or we could maybe refer to the component via git URI or should we just consider directly adding the components to the [ipaas-ui](https://github.com/redhat-ipaas/ipaas-ui) source tree?

**Comment by mattrpav** [comment]
Stan-

The 'modularization' is one of the tasks we are heads down on this week as part of our Sprint 9.5 plan. We are reviewing your notes and will have some feedback shortly. A short call might be in order if there are questions or we need to discuss.

Thanks,
-Matt

**Comment by gashcrumb** [comment]
@mattrpav Awesome!  Yeah, just wanted to get the conversation going :-)

**Comment by kahboom** [comment]
Thanks @gashcrumb - This is great; we want to get this started sooner rather than later as several requirements for this sprint are dependent on integration with the datamapper.

**Comment by mattrpav** [comment]
@kahboom @gashcrumb

1) Regarding removing BrowserModule from our code. This library provides baseline constructs such as ngFor (angular for loops) and ngIf (angular if statements) used commonly in angular component code. For example an ngIf statement is used to determine if the mapping detail panel should be visible or not depending on system state, and an example of an ngFor is the list of field components on a document card. We cannot remove this baseline functionality from the code. It is key functionality that makes angular components possible. Removing it would be akin to removing major critical portions of the struts framework.

2) We can package our code as a module as requested, we are seeing three options proposed by Stan: 

Option A: Add our code directly to the ipaas-ui source tree. 

Option B: Package our module up as an importable module. We think this is a cleaner and more viable option long term than Option A.

Option C: Package our module as described in Option B above, and publish the lib into an NPM registry with NPM formatting. This is not something we’d planned on tackling in our Sprint 10 workload.

Thoughts?

**Comment by gashcrumb** [comment]
> Regarding removing BrowserModule from our code. This library provides baseline constructs such as ngFor (angular for loops) and ngIf (angular if statements) used commonly in angular component code. For example an ngIf statement is used to determine if the mapping detail panel should be visible or not depending on system state, and an example of an ngFor is the list of field components on a document card. We cannot remove this baseline functionality from the code. It is key functionality that makes angular components possible. Removing it would be akin to removing major critical portions of the struts framework.

No, ngFor and that stuff is in CommonModule, BrowserModule has the bootstrappy stuff and isn't needed for normal components other than the app component.

Option B is probably the best, Option A would be the quick 'n dirty method :-)

**Comment by mattrpav** [comment]
Thanks for the heads up on CommonModule, we'll dig into that.

**Comment by mattrpav** [comment]
Confirmed we can remove BrowserModule.. it will be part of the 9.5 cut on Friday.

**Comment by mattrpav** [comment]
As discussed on the call:

- Angular2 module
- NPM defintion
- No need to publish to the central NPM repository at this time
