### ISSUE TITLE
[Discussion] Settle on datamapper 'groupId' and community domain

### ISSUE THREAD

**Issue by mattrpav** [redhat-ipaas/ipaas-datamapper#5]
Ideas:
  atlasmapper.io
  atlasmapping.io
  atlas.fabric8.io  (make it a sub-project of Fabric8?)

Other?

**Comment by chirino** [comment]
Do you own any of those domains?

**Comment by chirino** [comment]
any of those sound fine to me.

**Comment by mattrpav** [comment]
We don't own any of the domains currently, but last we checked they are available.

**Comment by chirino** [comment]
looks like google search for "atlas mapper" turns up some existing projects.

**Comment by chirino** [comment]
we got atlasmap.io lets go with that for now :)
