### ISSUE TITLE
Example datamapper configuration

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-datamapper#7]
For sprint 10 it talks about:

"Add a data mapping step, which should launch the Data Mapper UI
 Map name, title, and description fields in the Salesforce Contact" 

What would be the datamapper configuration we store in for this? I'm trying to put this into the example data.

**Comment by mattrpav** [comment]
Kurt: 

See: [atlasmapping-twitterStatusToSalesforceContact]( https://github.com/redhat-ipaas/ipaas-datamapper/blob/master/atlas2.itests.parent/atlas2.itests.twitterToSalesforce/src/test/resources/atlasmapping-twitterStatusToSalesforceContact.xml)

**Comment by KurtStam** [comment]
In this case the final configuration the UI produces for the twitter->salesforce mapping

**Comment by mattrpav** [comment]
Per IRC discussion..  TODO: provide completed mapping def'n for Twitter to SFDC.Contact in JSON format

**Comment by KurtStam** [comment]
thx @mattrpav, can you give us an idea when this might be ready?

**Comment by mattrpav** [comment]
[atlasmapping-twitterToSFDC.json.txt](https://github.com/redhat-ipaas/ipaas-datamapper/files/849167/atlasmapping-twitterToSFDC.json.txt)

**Comment by KurtStam** [comment]
Thanks @mattrpav

**Comment by KurtStam** [comment]
@mattrpav Can you send me an updated version of the JSON, using the new connector jar package names for twitter and salesforce? See https://github.com/redhat-ipaas/ipaas-datamapper/pull/21

**Comment by gashcrumb** [comment]
@mattrpav also, how does this configuration relate to the `MappingDefinition` type in the config on the UI side -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/models/mapping.definition.model.ts

**Comment by mattrpav** [comment]
@gashcrumb Jason updated the README.md here [https://github.com/redhat-ipaas/datamapper-ui](https://github.com/redhat-ipaas/datamapper-ui) to help w/ developer kickstart. 

Let me know if this covers it, or if it'd help to hop on a quick call to talk through it.

**Comment by KurtStam** [comment]
@mattrpav I think we now understand how it works. Can attach an updated version of the atlasmapping-twitterToSFDC.json.txt that has the new java package names of the twitter and SF connectors?

**Comment by mattrpav** [comment]
Kurt- Sure. Do you have the GAV coordinates for the models/POJOs?

**Comment by mattrpav** [comment]
I'm blocked due to unresolvable dependencies:

{noformat}
[ERROR] Failed to execute goal on project atlas.itests.ipaasTwitterToSFDC: Could not resolve dependencies for project io.atlasmap:atlas.itests.ipaasTwitterToSFDC:bundle:1.10.0-SNAPSHOT: Failed to collect dependencies at com.redhat.ipaas:twitter-mention-connector:jar:0.2.1: Failed to read artifact descriptor for com.redhat.ipaas:twitter-mention-connector:jar:0.2.1: Could not transfer artifact org.apache.camel:camel:pom:2.19.0-20170329.194614-132 from/to apache.snapshots (https://repository.apache.org/content/repositories/snapshots/): Connect to repository.apache.org:443 [repository.apache.org/207.244.88.143] failed: Operation timed out (Connection timed out) -> [Help 1]
{noformat}

**Comment by KurtStam** [comment]
@mattrpav , I've updated the runtime/pom.xml and with that you should be able to get past it.

**Comment by mattrpav** [comment]
Saw that.. working on building the test now.  Thanks

**Comment by mattrpav** [comment]
@KurtStam the provided dependencies do not include the SFDC POJO's. We need an implementation of the 'Contact' class

**Comment by KurtStam** [comment]
@mattrpav it's there but the java package is slightly different.

**Comment by mattrpav** [comment]
1. Created itest to use the new c.rh.ipaas.sfdc models
2. Updated JSON attached

[atlasmapping-iPaaSTwitterToSFDC.json.txt](https://github.com/redhat-ipaas/ipaas-datamapper/files/880528/atlasmapping-iPaaSTwitterToSFDC.json.txt)

**Comment by KurtStam** [comment]
@mattrpav thx!
