### ISSUE TITLE
Setup Project to Deploy to oss.sonatype.org

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-datamapper#8]
We should follow the following guide so that we can deploy to  oss.sonatype.org:
http://central.sonatype.org/pages/apache-maven.html

**Comment by mattrpav** [comment]
Hiram-

 I have some pom clean-ups to finish before cutting the release. Wrapping them up now, and I'll kick it off.

**Comment by mattrpav** [comment]
Deployed 1.9.5-SNAPSHOT
